name: tch_lab15:zadanie

on:
  workflow_dispatch:
  push:
    branches: ["*"]

#
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: # deklaracja macierz zmiennych
        include: # deklaracja zmiennych
          - dockerfile: ./Dockerfile
            context: nginx
            image:
            # image: docker.io/voiteckheir/tch_lab15:tch_lab15-nginx

          - dockerfile: ./Dockerfile
            context: mysql
            image:
            # image: docker.io/voiteckheir/tch_lab15:tch_lab15-mysql

          - dockerfile: ./Dockerfile
            context: php
            image:
            # image: docker.io/voiteckheir/tch_lab15:tch_lab15-php

          - dockerfile: ./Dockerfile
            context: phpmyadmin
            image:
            # image: docker.io/voiteckheir/tch_lab15:tch_lab15-phpmyadmin

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Buildx set-up
        uses: docker/setup-buildx-action@v2

      # Instalacja QEMU
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx

      # Logowanie do Dockerhub-a
      - name: Build and push dockerhub
        uses: docker/build-push-action@v3
        id: build
        with:
          platforms: linux/amd64,linux/arm64,
          context: "{{defaultContext}}:${{ matrix.context }}" # kontekst budowania obrazu Docker
          file: ${{matrix.dockerfile}} # plik Dockerfile, odpowiedni dla kontekstu
          push: true
          tags: |
            ${{matrix.image}}
          cache-from: type=registry,ref=${{matrix.image}}
          cache-to: type=registry,ref=${{matrix.image}},mode=max
